# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(:email => "krupa_17@hotmail.co.uk", :password => "Thakrar123", :password_confirmation => "Thakrar123")

Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
Topic.create(:title => "Alice in Wonderland",:body => "Young Alice is sitting by the river bank with her older sister, feeling bored; her sister's book has no pictures or conversation, and thus holds no interest for Alice. Suddenly, a white rabbit scampers back, proclaims that it is very late, and pulls a pocket watch out of its waistcoat. Though she initially does not notice the strangeness of a talking rabbit, when she sees the rabbit's clothes and watch, she becomes very interested. She follows the rabbit, hopping right down a deep rabbit hole after him, giving no thought of how she plans to get out again." ,:date => "2019/12/31")
